# add repositories
tap "buo/cask-upgrade"
tap "fujiwara/tap"

# packages
cask "xquartz"
brew "ascii"
brew "awscli"
brew "ecsta"
brew "ffmpeg"
brew "gh"
brew "gist"
brew "git"
brew "gnupg"
brew "go"
brew "hub"
brew "imagemagick"
brew "jq"
brew "libtool"
brew "lua"
brew "mas"
brew "nodejs"
brew "openssl"
brew "pandoc"
brew "perl"
brew "rustup"
brew "ssh-copy-id"
brew "vim"

# cask packages
cask "appcleaner"
cask "aws-vault"
cask "chrome-remote-desktop-host"
cask "clamxav"
cask "discord"
#cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "keepassx"
cask "postman"
cask "rectangle"
cask "skitch"
cask "slack"
cask "synology-drive"
cask "tailscale"
cask "the-unarchiver"
cask "vlc"
cask "zoom"

# packages on AppStore
mas "Twitter", id: 1482454543
mas "WireGuard", id: 1451685025
