# add repositories
tap "buo/cask-upgrade"
tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"

# packages
cask "xquartz"
brew "ascii"
brew "awscli"
brew "cabal-install"
brew "cairo"
brew "ctags"
brew "docker-clean"
brew "epubcheck"
brew "fontconfig"
brew "freetype"
brew "gd"
brew "gdbm"
brew "gdk-pixbuf"
brew "gettext"
brew "git"
brew "glib"
brew "gnupg"
brew "go"
brew "gobject-introspection"
brew "graphviz"
brew "harfbuzz"
brew "hub"
brew "icu4c"
brew "imagemagick", args: ["with-librsvg"]
brew "jpeg"
brew "jq"
brew "libassuan"
brew "libcroco"
brew "libgcrypt"
brew "libgpg-error"
brew "libksba"
brew "librsvg"
brew "libtool"
brew "libusb"
brew "libusb-compat"
brew "lua"
brew "mas"
brew "mercurial"
brew "oniguruma"
brew "openssl"
brew "pandoc"
brew "pinentry"
brew "pixman"
brew "pkg-config"
brew "pth"
brew "s3cmd"
brew "shared-mime-info"
brew "ssh-copy-id"
#brew "sshuttle"
brew "vim", args: ["HEAD", "with-lua", "with-python3"]

# cask packages
cask "alfred"
cask "appcleaner"
cask "charles"
cask "chrome-remote-desktop-host"
cask "clamxav"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "flash-player"
cask "gitter"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "java"
cask "karabiner"
cask "keepassx"
cask "mactex"
cask "mplayerx"
cask "opera"
cask "postman"
cask "sharemouse"
cask "silverlight"
cask "skype"
cask "slack"
cask "stoplight-studio"
cask "the-unarchiver"
cask "tiat"
cask "vagrant"
cask "virtualbox"
cask "vlc"

# packages on AppStore
mas "Tweetbot", id: 557168941
