[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  " Invoke post_source hooks on bootstrap
  autocmd VimEnter * call dein#call_hook('post_source')
'''

# United interface
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
  call denite#custom#alias('source', 'file/rec/git', 'file/rec')
  call denite#custom#var('file/rec/git', 'command',
  \  ['git', 'ls-files', '-co', '--exclude-standard'])
'''

# dependency of denite.nvim
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# dependency of denite.nvim
[[plugins]]
repo = 'roxma/nvim-yarp'

# MRU plugin for denite.nvim
[[plugins]]
repo = 'Shougo/neomru.vim'

# Auto completion
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

# Customize status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# Colorscheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

# Syntax highlighting for markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = '''
  " Disable auto folding for markdown files
  let g:vim_markdown_folding_disabled=1
'''

# Highlighting for CSV files
[[plugins]]
repo = 'mechatroner/rainbow_csv'
