[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  " Invoke post_source hooks on bootstrap
  autocmd VimEnter * call dein#call_hook('post_source')
'''

# United interface
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
  call denite#custom#alias('source', 'file/rec/git', 'file/rec')
  call denite#custom#var('file/rec/git', 'command',
  \  ['git', 'ls-files', '-co', '--exclude-standard'])
'''

# dependency of denite.nvim
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# dependency of denite.nvim
[[plugins]]
repo = 'roxma/nvim-yarp'

# MRU plugin for denite.nvim
[[plugins]]
repo = 'Shougo/neomru.vim'

# Control ctags
[[plugins]]
repo = 'szw/vim-tags'

# PEP8 based auto indentation
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# LSP (Language Server Protocol)
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

# LSP settings
[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  " Hide signcolumn.
  let g:lsp_diagnostics_signs_enabled = 0
  " Show diagnostics message to status line
  let g:lsp_diagnostics_echo_cursor = 1
  " Enable flake8 and mypy
  let g:lsp_settings = {
  \  'pylsp-all': {
  \    'workspace_config': {
  \      'pylsp': {
  \        'configurationSources': ['flake8'],
  \        'plugins': {
  \          'flake8': {
  \            'enabled': 1
  \          },
  \          'mccabe': {
  \            'enabled': 0
  \          },
  \          'pycodestyle': {
  \            'enabled': 0
  \          },
  \          'pyflakes': {
  \            'enabled': 0
  \          },
  \          'pylsp_mypy': {
  \            'enabled': 1
  \          }
  \        }
  \      }
  \    }
  \  }
  \}
'''
hook_post_source = '''
  " Highlight LSP warnings strongly (like errors)
  highlight link LspWarningHighlight Error
'''

# LSP-lightline bridge
[[plugins]]
repo = 'halkn/lightline-lsp'

# Auto completion
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

# Auto completion for LSP
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# Auto complete 'end' keyword (in Ruby)
[[plugins]]
repo = 'tpope/vim-endwise'

# Enhance increment/decrement feature
[[plugins]]
repo = 'nishigori/increment-activator'

# Reference viewer
[[plugins]]
repo = 'thinca/vim-ref'

# Ruby plugin for vim-ref
[[plugins]]
repo = 'yuku-t/vim-ref-ri'

# Customize status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \  'mode_map': {'c': 'NORMAL'},
  \  'active': {
  \    'right': [
  \      [ 'lsp_errors', 'lsp_warnings' ],
  \    ]
  \  },
  \  'component_expand': {
  \    'lsp_warnings': 'lightline_lsp#warnings',
  \    'lsp_errors':   'lightline_lsp#errors',
  \  },
  \  'component_type': {
  \    'lsp_warnings': 'warning',
  \    'lsp_errors':   'errors',
  \  },
  \}
'''

# Colorscheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

# Colorscheme
[[plugins]]
repo = 'w0ng/vim-hybrid'

# Highlights quickfix errors
[[plugins]]
repo = 'cohama/vim-hier'

# Utilities for Ruby on Rails
[[plugins]]
repo = 'tpope/vim-rails'

# Syntax highlighting for markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = '''
  " Disable auto folding for markdown files
  let g:vim_markdown_folding_disabled=1
'''

# Syntax highlighting for code-blocks in markdown
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'

# Highlighting for CSV files
[[plugins]]
repo = 'mechatroner/rainbow_csv'
