#!/bin/sh

cd `dirname ${0}`/..  # Move dotfiles directory

rm -f $HOME/.zshrc  # Remove .zshrc generated by features/common-utils

apt update
apt install -y jq less vim

if ! type diff-highlight > /dev/null 2>&1 ; then
    apt install -y python3-pip
    pip3 install --upgrade diff-highlight
fi

echo ""
echo "Setup submodules ..."
git submodule update --init
git submodule foreach git checkout master
git submodule foreach git pull

echo ""
echo "Setup \$HOME/bin ..."
ln -s $PWD/bin $HOME/bin

echo ""
echo "Creating dotfile symlinks ..."
for dotfile in _?*
do
    dotname=`echo $dotfile | sed -e "s/^_/./"`
    if [ $dotfile != '..' ] && [ $dotfile != '.hg' ]; then
        if [ -L $HOME/$dotname ]; then
            cat /dev/null  # noop
        elif [ -e $HOME/$dotname ]; then
            echo "Ignore $HOME/$dotname (already exists)"
        else
            echo "Creating $HOME/$dotname ..."
            ln -s "$PWD/$dotfile" $HOME/$dotname
        fi
    fi
done

echo ""
echo "Setup vim extensions ..."
vim -N -u $HOME/.vimrc -c 'call dein#update()' -c 'qall!' -U NONE -i NONE -V1 -e -s

