#!/bin/sh

cd `dirname ${0}`/..  # Move dotfiles directory

# fetch the latest dotfiles (if cached)
git checkout .; git pull

rm -f $HOME/.zshrc  # Remove .zshrc generated by features/common-utils
rm -f /etc/apt/apt.conf.d/docker-clean  # Remove this file to make apt cache mechanism available

apt update
apt install -y jq less vim zsh

if ! type diff-highlight > /dev/null 2>&1 ; then
    apt install -y python3-pip
    pip3 install --upgrade diff-highlight
fi

echo ""
echo "Setup \$HOME/bin ..."
ln -s $PWD/bin $HOME/bin

if [ ! -z $GIT_EMAIL ]; then
    echo ""
    echo "Setup .gitconfig ..."
    cp $PWD/_gitconfig $HOME/.gitconfig
    echo '[user]' >> $HOME/.gitconfig
    echo '    email = ' $GIT_EMAIL >> $HOME/.gitconfig
fi

echo ""
echo "Creating dotfile symlinks ..."
for dotfile in _?*
do
    dotname=`echo $dotfile | sed -e "s/^_/./"`
    if [ $dotfile != '..' ] && [ $dotfile != '.hg' ]; then
        if [ -L $HOME/$dotname ]; then
            cat /dev/null  # noop
        elif [ -e $HOME/$dotname ]; then
            echo "Ignore $HOME/$dotname (already exists)"
        else
            echo "Creating $HOME/$dotname ..."
            ln -s "$PWD/$dotfile" $HOME/$dotname
        fi
    fi
done

echo ""
echo "Setup vim extensions ..."
vim -N -u $HOME/.vimrc -c 'call dein#update()' -c 'qall!' -U NONE -i NONE -V1 -e -s

